### PR TITLE
fix(datalist accessibility):  h2 used as child element

### LINKED ISSUE #1114: DataList examples and a11y documentation
Currently, some screen readers like JAWS and NVDA don't provide any indication when navigating between list items in the DataList component. A simple way to provide better separation of list items is to define the primary content section as a heading. 

As part of this issue, the DataList component should include additional examples and documentation so that consumers understand how to improve screen reader accessibility:

1. New example using `<h2>` element
    - Make a duplicate of Data List Simple, and use `<h2>` as the element for either the `div.pf-c-data-list__cell` element or the child `<span>` of that `<div>`
    - Include an Accessibility documentation section for that example that explains the importance of including headers in the DataList component when more than a primary content section is included. For example:
      >  When a list item includes more than one block of content, it can be difficult for some screen reader users to discern where one list item ends and the next one begins. A simple way to provide  better separation of list items is to define the primary content section as a heading. Headings are useful for indicating a new section of contents, but also provide an easy way for screen reader users to navigate to specific sections on the page. The heading level should be based on the context in which the DataList component is being used. For example, if the heading for the section that contains the DataList is a level 3, then `<h4>` elements should be used in the DataList list items. 
2. New example using just `<li>` elements
    - It's possible to create a datalist that doesn't include the wrapping elements inside the `<li>`: `<div class="pf-c-data-list__cell">`. Create a new example that illustrates this.

### PR DESCRIPTION
**Pull request by jenny-s51**
closes #1114   -- adds changes mentioned in part 1.

### CODE REVIEW

**Comment by jgiardino** [comment]
Great job with this one! The example looks good! I just have a few suggestions for tweaking the documentation and example label. I'll make inline comments for those...

File: src/patternfly/components/DataList/examples/index.js [hunk 1]
```diff
@@ -33,6 +37,13 @@ export default (props) => {
       <Example heading="Data list simple" handlebars={DataListSimpleExampleRaw} docs={DataListSimpleExampleDoc}>
         {dataListSimpleExample}
       </Example>
+      <Example
+        heading="Data list simple h2: screen reader accessible"
```
Comment (jgiardino) [inline src/patternfly/components/DataList/examples/index.js]: I suggest naming this example something like "Data list simple with headings", and then leave it to the documentation to explain why headings are beneficial.

File: src/patternfly/components/DataList/docs/data-list-simple-h2.md [hunk 2]
```diff
@@ -0,0 +1,4 @@
+### Usage
+| Class | Applied to | Outcome |
+| ------ | -- | -- |
+| `.pf-c-data-list__cell` > *    | `h2`  | Provides better separation of list items by defining the primary content section as a heading. Easy way for screen reader users to navigate to specific sections on the page. Heading level should be based on the context in which the DataList component is being used. E.g., if the heading for the section that contains the DataList is a level 3, then `h4` elements should be used in the DataList items. **Required** |
```
Comment (jgiardino) [inline src/patternfly/components/DataList/docs/data-list-simple-h2.md]: These tables are primarily used to describing what classes or attributes are can or should be used in the component. But this example is just illustrating how the heading element can be incorporated into the datalist html structure.

I would remove the table and just have a paragraph that explains why headings are beneficial. And then the end of the explanation can include a statement like "Refer to the [example label] for an example of how a heading can be used in this component.

Also remove the "**Required**". This is used to indicate classes or attributes that result in the component not being usable or rendered as expected.

Comment (jgiardino) [reply src/patternfly/components/DataList/docs/data-list-simple-h2.md]: I take back my suggestion to include this statement, "Refer to the [example label] for an example of how a heading can be used in this component."

Sometimes our component documentation is included at the end of the page, but in this case it's not and is adjacent to the example. So we can leave that statement out.

File: src/patternfly/components/DataList/examples/index.js (hunk 1 above)
Comment (jenny-s51) [reply src/patternfly/components/DataList/examples/index.js]: sure thing!

**Comment by jenny-s51** [comment]
@jgiardino should be all set I think? let me know if there's anything else :)

File: src/patternfly/components/AboutModalBox/examples/index.js [hunk 3]
```diff
@@ -6,7 +6,7 @@ import AboutModalBoxExample from './about-modal-box-example.hbs';
 
 export const Docs = docs;
 
-export default (props) => {
+export default props => {
```
Comment (christiemolloy) [inline src/patternfly/components/AboutModalBox/examples/index.js]: @jenny-s51 not sure where this change came from, but i dont think its part of this PR so you can remove this change?

File: src/patternfly/components/DataList/docs/data-list-simple-h2.md [hunk 4]
```diff
@@ -0,0 +1,2 @@
+### Usage
+When a list item includes more than one block of content, it can be difficult for some screen reader users to discern where one list item ends and the next one begins. A simple way to provide better separation of list items is to define the primary content section as a heading. Headings are useful for indicating a new section of contents, but also provide an easy way for screen reader users to navigate to specific sections on the page. The heading level should be based on the context in which the DataList component is being used. For example, if the heading for the section that contains the DataList is a level 3, then `h4` elements should be used in the DataList list items.
```
Comment (christiemolloy) [inline src/patternfly/components/DataList/docs/data-list-simple-h2.md]: @jgiardino in `When a list item includes more than one block of content` do you mean when a list includes more than one list item?

File: src/patternfly/components/Tabs/examples/index.js [hunk 5]
```diff
@@ -43,7 +43,7 @@ import docs from '../docs/code.md';
 export const headingText = 'Tabs';
 export const Docs = docs;
 
-export default (props) => {
+export default props => {
```
Comment (christiemolloy) [inline src/patternfly/components/Tabs/examples/index.js]: @jenny-s51 also not sure how this change got in?

File: src/patternfly/components/DataList/docs/data-list-simple-h2.md (hunk 4 above)
Comment (christiemolloy) [reply src/patternfly/components/DataList/docs/data-list-simple-h2.md]: @jgiardino ^

Comment (jgiardino) [reply src/patternfly/components/DataList/docs/data-list-simple-h2.md]: For example, this `<li>` includes two separate `<div>`s. When a `<li>` includes more than one block of content, it might not be obvious which blocks are grouped together inside a list item. Some screen readers like VO announce the beginning/end of a list item, but for some screen readers, this is not announced. Using headings is an easy way to organize the information in a way that's more obvious in some screen readers.

```
<li class="pf-c-data-list__item" aria-labelledby="simple-item1">
    <div class="pf-c-data-list__item-row">
      <div class="pf-c-data-list__item-content">
        <div class="pf-c-data-list__cell">
          <span id="simple-item1">Primary content</span>
        </div>
        <div class="pf-c-data-list__cell">
          Secondary content
        </div>
      </div>
    </div>
  </li>
```
